### ISSUE TITLE
Toolbar text is overlay ed by Notifications bar

### ISSUE THREAD

**Issue by vrajeshkanna** [Codebrahma/whatsquick-mobile#3]
<img width="540" alt="screenshot 14-jan-2018 9_15_58 am" src="https://user-images.githubusercontent.com/397057/34912625-f00b5d40-f90b-11e7-8413-ec09fdb6a35c.png">

**Comment by Arjun-sna** [comment]
@vrajeshkanna Please post the details testing device you used.

**Comment by vrajeshkanna** [comment]
@Arjun-sna We may close it as it is an expo issue
